[package]
name = "widgets_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
cxx   = "1"
autocxx = "0.27"
chrono = "0.4"

[build-dependencies]
autocxx-build = "0.27"
cxx-build     = "1"
pkg-config    = "0.3"
